try:
    # -- Distribution mode --
    # import from _version.py generated by setuptools_scm during release
    from ._version import __version__
except ImportError:
    # -- Source mode --
    # use setuptools_scm to get the current version from src using git
    from pathlib import Path as _Path

    from setuptools_scm import get_version as _gv

    __version__ = _gv(_Path(__file__).parent.parent.parent)
